-- Sample data: 3 periods × 5 students, 2 assignments, 2 entries per student, links + tags

TRUNCATE writing_tags, source_links, entries, assignments, students RESTART IDENTITY CASCADE;

INSERT INTO students (first_name, last_name, period, iep_flags) VALUES
  ('Ava', 'Allen', 1, NULL),
  ('Ben', 'Brooks', 1, 'Extended time for writing'),
  ('Chloe', 'Carter', 1, NULL),
  ('Dylan', 'Diaz', 1, NULL),
  ('Eva', 'Edwards', 1, 'Preferential seating'),
  ('Finn', 'Foster', 2, NULL),
  ('Grace', 'Garcia', 2, NULL),
  ('Henry', 'Hughes', 2, 'Speech support — clarify prompts verbally'),
  ('Ivy', 'Ingram', 2, NULL),
  ('Jack', 'Jenkins', 2, NULL),
  ('Kate', 'King', 3, NULL),
  ('Liam', 'Lopez', 3, NULL),
  ('Mia', 'Murphy', 3, 'Chunk written responses'),
  ('Noah', 'Nguyen', 3, NULL),
  ('Olivia', 'Ortiz', 3, NULL);

INSERT INTO assignments (name, unit, aks_standard, prompt_text, date_assigned) VALUES
  (
    'Peppered Moth Gwinnett Writes Practice',
    'Evolution',
    'SB5. Students will evaluate the role of natural selection in the development of a population over time.',
    'Use evidence from the peppered moth case study to explain how the environment affected which traits survived. Cite at least one source by name.',
    '2025-09-08'
  ),
  (
    'Trophic Cascade Quick Write',
    'Ecology',
    'SB4. Students will analyze relationships among organisms in an ecosystem.',
    'Describe how removing one species can change an ecosystem. Include a claim, evidence from class sources, and reasoning.',
    '2025-10-01'
  );

-- Two entries per student: assignment 1 (Sept) and assignment 2 (Oct); a few recent dates for analytics
INSERT INTO entries (student_id, assignment_id, date_submitted, writing_sample, student_feedback, teacher_notes, word_count, flagged_for_followup) VALUES
  (1, 1, '2025-09-15', 'The peppered moth shows natural selection. Light moths hid on clean bark while dark moths blended with soot. Over time the population shifted.', 'Glow: Clear cause and effect. Grow: Name your graph source explicitly.', 'Model sentence stems next time.', 23, false),
  (1, 2, '2025-10-08', 'If wolves leave Yellowstone elk eat more plants. Streams change because plants hold soil. This is a cascade through the food web.', 'Glow: Connected species to habitat. Grow: Add one numeric detail from the reading.', NULL, 22, false),
  (2, 1, '2025-09-16', 'Pollution made trees darker so dark moths survived better. That is adaptation to the environment in Britain during the Industrial Revolution.', 'Glow: Strong context. Grow: Use the word selective pressure.', 'Check understanding of adaptation vs acclimation.', 21, true),
  (2, 2, '2025-10-09', 'Removing sea otters lets urchins explode and kelp forests shrink. The ecosystem loses structure and fish lose nursery habitat.', 'Glow: Two-step reasoning. Grow: Cite the kelp article title.', NULL, 19, false),
  (3, 1, '2025-09-15', 'Natural selection means heritable traits that help survival become common. Moth color matched tree color so birds ate fewer camouflaged moths.', 'Glow: Defines selection well. Grow: Tie back to frequency change.', NULL, 21, false),
  (3, 2, '2025-10-07', 'Apex predators control herbivores. Without them plants get overgrazed and biodiversity drops in the grassland example.', 'Glow: Clear claim. Grow: Add evidence from the food web diagram.', 'Encourage labeling trophic levels.', 16, false),
  (4, 1, '2025-09-17', 'The textbook graph shows dark moth increase after 1850. The environment selected for camouflage on polluted trees.', 'Glow: Used the graph. Grow: Explain mechanism in one more sentence.', NULL, 17, false),
  (4, 2, '2025-10-10', 'Keystone species have outsized effects. Starfish removal from tide pools changed which species dominated the rocky shore.', 'Glow: Good example choice. Grow: Name the Pisaster study.', NULL, 17, true),
  (5, 1, '2025-09-16', 'Birds are the selective agent. They ate visible moths. Surviving moths reproduced and passed color genes to offspring.', 'Glow: Mentions reproduction. Grow: Link to allele frequency.', 'Review genetics vocabulary.', 18, false),
  (5, 2, '2025-10-08', 'Trophic cascade moves energy and matter through levels. Losing a producer hits every consumer above it eventually.', 'Glow: Big picture. Grow: Give one concrete species chain.', NULL, 17, false),
  (6, 1, '2025-09-18', 'Industrial melanism is the pattern. Dark phenotype rose where soot darkened bark then fell when air cleaned up.', 'Glow: Historical arc. Grow: Cite the recovery data table.', NULL, 18, false),
  (6, 2, '2025-10-11', 'Invasive species can remove natives and simplify food webs. That makes the system less stable during drought or disease.', 'Glow: Risk thinking. Grow: Add local Georgia example if possible.', NULL, 19, false),
  (7, 1, '2025-09-15', 'The moth story supports Darwin because variation existed and the environment changed which variant survived and reproduced most.', 'Glow: Links to Darwin. Grow: Define fitness in your own words.', NULL, 18, false),
  (7, 2, '2025-10-09', 'Primary producers capture energy. If they crash every higher level loses energy input and population sizes fall.', 'Glow: Energy angle. Grow: Mention photosynthesis once.', NULL, 17, false),
  (8, 1, '2025-09-17', 'Dark moths had higher survival in polluted forests because predators could not see them as easily on dark backgrounds.', 'Glow: Mechanism clear. Grow: Add a counterexample from clean forests.', 'Pair with sentence frame.', 19, true),
  (8, 2, '2025-10-10', 'Herbivore overpopulation strips vegetation then soil erodes. Rivers carry sediment and water quality declines downstream.', 'Glow: Cause chain. Grow: Cite the river turbidity source.', NULL, 15, false),
  (9, 1, '2025-09-16', 'Frequency of alleles changed when selection favored dark coloring. That is evolution in a population not just individual change.', 'Glow: Allele language. Grow: Shorten long sentences.', NULL, 19, false),
  (9, 2, '2025-10-08', 'Detritivores recycle nutrients. If they decline nutrients lock in dead material and plant growth slows.', 'Glow: Nutrient cycling. Grow: Connect to decomposers lesson.', NULL, 15, false),
  (10, 1, '2025-09-18', 'Peppered moths are a classic example because data spans decades and matches prediction from natural selection theory.', 'Glow: Meta-level insight. Grow: Add one data point from the graph.', NULL, 17, false),
  (10, 2, '2025-10-11', 'Removing sharks can increase ray populations which then reduce shellfish. Fisheries and habitats both change.', 'Glow: Human relevance. Grow: Label claim vs evidence.', NULL, 15, false),
  (11, 1, '2025-09-15', 'Selection acts on phenotypes. Moth color is phenotype tied to genotype and the environment determines which phenotype hides best.', 'Glow: Phenotype link. Grow: Simplify jargon for clarity.', NULL, 19, false),
  (11, 2, '2025-10-07', 'Biodiversity buffers ecosystems. More species mean more pathways for energy flow if one pathway is disrupted.', 'Glow: Stability idea. Grow: Use one vocabulary term from the rubric.', NULL, 16, false),
  (12, 1, '2025-09-17', 'The moth case shows rapid change when selection is strong. Clean air reversed selection pressure toward lighter moths again.', 'Glow: Reversible change noted. Grow: Quantify with percentages if available.', NULL, 19, false),
  (12, 2, '2025-10-10', 'Food web models predict indirect effects. A small change at one node can ripple widely especially with few redundant links.', 'Glow: Network thinking. Grow: Name two nodes from class model.', NULL, 20, false),
  (13, 1, '2025-09-16', 'Evidence includes museum records and field surveys showing moth color ratios shifting with pollution levels over time.', 'Glow: Evidence types. Grow: Explain why surveys matter.', NULL, 17, false),
  (13, 2, '2025-10-09', 'Competitive release happens when a dominant competitor disappears. Remaining species expand into open niche space quickly.', 'Glow: Niche vocabulary. Grow: Tie to trophic cascade definition.', NULL, 16, false),
  (14, 1, '2025-09-18', 'Camouflage is an adaptation shaped by predation. Moths that matched bark avoided bird attacks and lived to reproduce.', 'Glow: Adaptation defined. Grow: Add source citation.', NULL, 18, false),
  (14, 2, '2026-03-18', 'Ecosystem engineers like beavers reshape habitats. Removing them changes water flow and therefore plant and fish communities.', 'Glow: Engineer concept. Grow: One more concrete beaver behavior.', NULL, 17, true),
  (15, 1, '2025-09-15', 'Students should connect genotype to phenotype to selection. The moth allele frequencies track environmental change.', 'Glow: Genotype mention. Grow: Stay in student voice; avoid meta commentary.', 'Discuss audience — rewrite as first person.', 15, true),
  (15, 2, '2026-03-19', 'Trophic cascades connect predators to producers indirectly. Even small shifts can reorganize community structure when links are tight.', 'Glow: Strong synthesis. Grow: Cite one class source by name.', NULL, 18, false);

INSERT INTO source_links (entry_id, label, url) VALUES
  (1, 'Source 1 - Peppered Moth Graph', 'https://drive.google.com/file/d/example-moth-graph'),
  (1, 'Source 2 - Industrial Revolution Context', 'https://drive.google.com/file/d/example-context'),
  (2, 'Source 1 - Yellowstone Trophic Cascade', 'https://drive.google.com/file/d/example-yellowstone'),
  (3, 'Source 1 - Peppered Moth Reading', 'https://drive.google.com/file/d/example-reading'),
  (4, 'Source 1 - Kelp Forest Article', 'https://drive.google.com/file/d/example-kelp'),
  (5, 'Source 1 - Class Anchor Chart', 'https://drive.google.com/file/d/example-chart'),
  (6, 'Source 1 - Food Web Diagram', 'https://drive.google.com/file/d/example-web'),
  (7, 'Source 1 - Textbook Figure 12.4', 'https://drive.google.com/file/d/example-fig'),
  (8, 'Source 1 - Pisaster Study Notes', 'https://drive.google.com/file/d/example-pisaster'),
  (9, 'Source 1 - Selection Vocabulary Slide', 'https://drive.google.com/file/d/example-slide'),
  (10, 'Source 1 - Energy Pyramid Handout', 'https://drive.google.com/file/d/example-pyramid'),
  (11, 'Source 1 - Melanism Data Table', 'https://drive.google.com/file/d/example-table'),
  (12, 'Source 1 - Invasive Species Map', 'https://drive.google.com/file/d/example-map'),
  (13, 'Source 1 - Darwin Notebook Excerpt', 'https://drive.google.com/file/d/example-darwin'),
  (14, 'Source 1 - Primary Production Reading', 'https://drive.google.com/file/d/example-pp'),
  (15, 'Source 1 - Predation Simulation', 'https://drive.google.com/file/d/example-sim'),
  (16, 'Source 1 - River Turbidity Graph', 'https://drive.google.com/file/d/example-river'),
  (17, 'Source 1 - Allele Frequency Sheet', 'https://drive.google.com/file/d/example-allele'),
  (18, 'Source 1 - Decomposer Lab', 'https://drive.google.com/file/d/example-lab'),
  (19, 'Source 1 - Long-term Moth Survey', 'https://drive.google.com/file/d/example-survey'),
  (20, 'Source 1 - Shark Ray Article', 'https://drive.google.com/file/d/example-shark'),
  (21, 'Source 1 - Phenotype Genotype Graphic', 'https://drive.google.com/file/d/example-pg'),
  (22, 'Source 1 - Biodiversity Stability', 'https://drive.google.com/file/d/example-bio'),
  (23, 'Source 1 - Recovery Era Data', 'https://drive.google.com/file/d/example-recovery'),
  (24, 'Source 1 - Network Model Sheet', 'https://drive.google.com/file/d/example-net'),
  (25, 'Source 1 - Museum Records Pack', 'https://drive.google.com/file/d/example-museum'),
  (26, 'Source 1 - Competitive Release Notes', 'https://drive.google.com/file/d/example-cr'),
  (27, 'Source 1 - Camouflage Video', 'https://drive.google.com/file/d/example-video'),
  (28, 'Source 1 - Beaver Hydrology Map', 'https://drive.google.com/file/d/example-beaver'),
  (29, 'Source 1 - Allele Tracking Worksheet', 'https://drive.google.com/file/d/example-track'),
  (30, 'Source 1 - Trophic Model Exit Ticket', 'https://drive.google.com/file/d/example-exit');

INSERT INTO writing_tags (entry_id, claim_present, evidence_cited, explanation_present, source_named, response_incomplete, ai_flag, notes) VALUES
  (1, true, true, true, true, false, false, 'Strong CER alignment'),
  (2, true, true, true, false, false, false, 'Add explicit source title'),
  (3, true, true, false, true, false, false, NULL),
  (4, true, true, true, false, false, false, NULL),
  (5, true, false, true, false, true, false, 'Evidence thin'),
  (6, true, true, true, false, false, false, NULL),
  (7, true, true, true, false, false, false, NULL),
  (8, true, true, true, false, true, false, 'Missing source name'),
  (9, true, true, true, true, false, false, NULL),
  (10, true, false, true, false, true, false, NULL),
  (11, true, true, true, true, false, false, NULL),
  (12, true, true, true, false, false, false, NULL),
  (13, true, true, true, true, false, false, NULL),
  (14, true, true, false, false, false, false, NULL),
  (15, true, true, true, false, false, true, 'Unusually polished phrasing — verify in conference'),
  (16, true, true, true, false, false, false, NULL),
  (17, true, true, true, true, false, false, NULL),
  (18, true, false, true, false, false, false, NULL),
  (19, true, true, true, false, false, false, NULL),
  (20, true, true, true, false, true, false, NULL),
  (21, true, true, true, false, false, false, NULL),
  (22, true, true, true, false, false, false, NULL),
  (23, true, true, true, true, false, false, NULL),
  (24, true, true, true, false, false, false, NULL),
  (25, true, true, true, false, false, false, NULL),
  (26, true, true, true, false, false, false, NULL),
  (27, true, false, true, false, true, false, NULL),
  (28, true, true, true, false, false, false, NULL),
  (29, true, true, false, false, false, false, NULL),
  (30, true, true, true, false, false, false, NULL);
